print (' APP PARA CALCULAR AUMENTO DE SALÁRIO ')
nome = input ('Nome do Funcionário: ')
salario = float (input('Salário do Funcionario: '))
aumento = float (input('Percetual do aumento: '))
print ('Valor total é: ', salario + (salario * aumento / 100))
